spring:
  application:
    name: generics-demo
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enable: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true
    repositories:
      bootstrap-mode: default
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
